name = "snip-edge"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "URL_CACHE"
id = "b2f671c466d8403180a3644afe9e614d"
preview_id = "b2f671c466d8403180a3644afe9e614d"

[vars]
API_ORIGIN_URL = "https://snap-api-o3sv.onrender.com"
APP_URL = "http://localhost:5173"

[[analytics_engine_datasets]]
binding = "ANALYTICS_ENGINE"
dataset = "snap_click_events"

[triggers]
crons = ["*/1 * * * *"]
